/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class application_controller_processor_ProcessingRunnable */

#ifndef _Included_application_controller_processor_ProcessingRunnable
#define _Included_application_controller_processor_ProcessingRunnable
#ifdef __cplusplus
extern "C" {
#endif

//#ifndef DEBUG
//  #define DEBUG
//#endif

#define GS_SUCCESS 1
#define GS_FAILURE -1

extern int pageCount;
extern int convertPDF(const char* in, const char* out);

extern jobject createViewableImageFile(JNIEnv *, jobject, jstring);
extern jobject processImageFile(JNIEnv *, jobject, jstring);

/*
 * Class:     application_controller_processor_ProcessingRunnable
 * Method:    processImageFile
 * Signature: (Ljava/lang/String;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_application_controller_processor_ProcessingRunnable_processImageFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     application_controller_processor_ProcessingRunnable
 * Method:    getViewableImageFile
 * Signature: (Ljava/lang/String;)Ljava/io/File;
 */
JNIEXPORT jobject JNICALL Java_application_controller_processor_ProcessingRunnable_createViewableImageFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
